name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2 #pour recuperer le code source 
      name: checkout source code 
    - uses: ./action-a
      env:
        MY_NAME: "Ilies"
